### ISSUE TITLE
Cannot read properties of undefined (reading 'setup')

### ISSUE THREAD

**Issue by marcelino-borges** [microsoft/ApplicationInsights-node.js#1077]
Hi!

I'm starting to use App Insights in my NodeJS API, but I have this error that I just can't understand.
I had implemented a few tracking calls, but for now I removed them all and left just the setup into my `src/server.ts`.

In all the examples I find I see this 
```javascript
let appInsights = require('applicationinsights');
```

So in my code I'm importing like
```javascript
import appInsights from "applicationinsights";
```

So I just set things up like this
```javascript
  appInsights
    .setup(process.env.APP_INSIGHTS_CONN_STRING)
    .setAutoDependencyCorrelation(true)
    .setAutoCollectConsole(true, true)
    .setSendLiveMetrics(true)
    .start();
```

Then I get this error
```
TypeError: Cannot read properties of undefined (reading 'setup')
    at Object.<anonymous> (path-to-my-app\users-api\src\server.ts:23:6)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module.m._compile (path-to-my-app\users-api\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.require.extensions.<computed> [as .ts] (path-to-my-app\users-api\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (path-to-my-app\users-api\node_modules\ts-node\src\bin.ts:649:14)
    at bootstrap (path-to-my-app\users-api\node_modules\ts-node\src\bin.ts:95:10)
    at main (path-to-my-app\users-api\node_modules\ts-node\src\bin.ts:55:10)
    at Object.<anonymous> (path-to-my-app\users-api\node_modules\ts-node\src\bin.ts:800:3)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
[nodemon] app crashed - waiting for file changes before starting...
```

Dependencies I assured to have installed for the AppInsights (of course I have others, but these ones might be of your interest):

```json
/* package.json */
{
  (...)
  "dependencies": {
    "@azure/service-bus": "^7.8.0",
    "applicationinsights": "^2.4.2",
  },
  "devDependencies": {
    "@types/applicationinsights": "^0.20.0",
    "@types/node": "^18.11.17",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4"
  }
}
```

Node version:
```powershell
node -v
v16.19.0
```

NPM version:
```powershell
npm -v
8.19.3
```

Am I doing something wrong or not seeing anything?

**Comment by marcelino-borges** [comment]
Ok, so I just realized there is no `default` export in the lib...

My fix was to import like this:
```javascript
import * as appInsights from "applicationinsights";
```
