### ISSUE TITLE
Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by brianpham93** [microsoft/ApplicationInsights-node.js#1249]
I use `winston` and `winston-azure-application-insights` to log directly to application insights
I'm getting this error when log an object that contains BigInt data

```shel
ApplicationInsights:Failed to serialize payload [
  TypeError: Do not know how to serialize a BigInt
      at JSON.stringify (<anonymous>)
      at Util.stringify (./my-project/node_modules/applicationinsights/out/Library/Util.js:373:25)
      at EnvelopeFactory.truncateProperties (./my-project/node_modules/applicationinsights/out/Library/EnvelopeFactory.js:135:60)
      at EnvelopeFactory.createTraceData (./my-project/node_modules/applicationinsights/out/Library/EnvelopeFactory.js:153:33)
      at EnvelopeFactory.createEnvelope (./my-project/node_modules/applicationinsights/out/Library/EnvelopeFactory.js:24:40)
      at TelemetryClient.track (./my-project/node_modules/applicationinsights/out/Library/TelemetryClient.js:134:44)
      at TelemetryClient.trackTrace (./my-project/node_modules/applicationinsights/out/Library/TelemetryClient.js:60:14)
      at ./my-project/node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/winston.sub.js:55:20
      at Array.forEach (<anonymous>)
      at subscriber (./my-project/node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/winston.sub.js:40:13)
```
Does ApplicationInsights support BigInt or is there anything wrong with the way i'm logging data ?

Version: 2.9.1
Host: macOS 14, Apple Silicon

**Comment by hectorhdzg** [comment]
@brianpham93 looks like the issue is in JSON.stringify, after a quick internet search looks like some type replacement can be done to prevent this error, can you share some sample winston log we can use to reproduce?

**Comment by JacksonWeber** [comment]
@brianpham93 Did you have any luck with your serialization issue?

**Comment by brianpham93** [comment]
> @brianpham93 Did you have any luck with your serialization issue?

i'm using this working around temporarily

```js
BigInt.prototype.toJSON = function () {
	return this.toString();
};
```

**Comment by brianpham93** [comment]
@JacksonWeber So far i haven't found out any issue with current approach

**Comment by JacksonWeber** [comment]
@brianpham93 Awesome! Mind if I mark this issue as complete in that case?

**Comment by brianpham93** [comment]
@JacksonWeber No issue. It would be better if this is supported natively in app insights via a separate PR
