### ISSUE TITLE
Receiving "Can't set headers after they are sent." error

### ISSUE THREAD

**Issue by erikschlegel** [Microsoft/ApplicationInsights-node.js#252]
I'm seeing the intermittent error listed below whenever I call `appInsights.client.trackRequest(req, res);` 

Any guidance would be very helpful? 

Thanks,

Erik

Error
```
Error: Can't set headers after they are sent.
    at new Error (native)
    at Error.AppInsightsAsyncCorrelatedErrorWrapper (/gitRepo/appinsights-test-node/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:141:18) [<root>]
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11) [<root>]
    at expressInit (/gitRepo/appinsights-test-node/node_modules/express/lib/middleware/init.js:30:42) [<root>]
    at Layer.handle [as handle_request] (/gitRepo/appinsights-test-node/node_modules/express/lib/router/layer.js:95:5) [<root>]
```

**Comment by OsvaldoRosado** [comment]
your Application Map)
n your Application Map)Please call trackRequest as soon as possible in your code. This is a sign trackRequest is being called sometime after you have started sending a response back.

Calling trackRequest as soon as you get the req/res pair from your server object is necessary so that we can accurately record the amount of time processing took for the request. It is also necessary that trackRequest receives the res object before the response has begun being sent so that we can add correlation headers to your response (this allows you to correlate a request from one server to another)

**Comment by OsvaldoRosado** [comment]
If possible, consider using automatic request collection, it will handle all of this for you - removing the need for manual trackRequest calls :smile:

**Comment by OsvaldoRosado** [comment]
Closing this for now. Feel free to re-open if this didn't help resolve the issue!
