### ISSUE TITLE
Error: Range Not Satisfiable

### ISSUE THREAD

**Issue by msternik** [Microsoft/ApplicationInsights-node.js#275]
Hi, I have been getting this error recently:

Error: Range Not Satisfiable
    at new Error (native)
    at Error.AppInsightsAsyncCorrelatedErrorWrapper 

Any idea what could be wrong?

Thanks!

**Comment by OsvaldoRosado** [comment]
Do you have more of the stack trace? Seeing `Error.AppInsightsAsyncCorrelatedErrorWrapper` at the top isn't necessarily a sign that the error comes from this SDK, it's just because we wrap around exceptions to be able to collect them with the asynchronous context (to correlate with the correct incoming request).

**Comment by msternik** [comment]
@OsvaldoRosado thanks for prompt response, I attach more detailed stack trace, please note I removed some info (like folder names).

2017-06-09 18:35:03.507] [ERROR] console - Error: Range Not Satisfiable
    at new Error (native)
    at Error.AppInsightsAsyncCorrelatedErrorWrapper (/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:141:18) []
    at SendStream.error (/node_modules/send/lib/send.js:145:16) []
    at SendStream.send (/node_modules/send/lib/send.js:370:19) []
    at /node_modules/send/lib/send.js:322:10 []
    at Zone.runTask (/node_modules/zone.js/dist/zone-node.js:151:47) [<root> => ]
    at ZoneTask.invoke (/node_modules/zone.js/dist/zone-node.js:345:33) [<root>]
    at data.args.(anonymous function) (node_modules/zone.js/dist/zone-node.js:1239:25) [<root>]
    at FSReqWrap.oncomplete (fs.js:123:15) [<root>]

**Comment by OsvaldoRosado** [comment]
Looks like you might be running into a problem described about send.js here: https://stackoverflow.com/a/38499519 rather than with the AI SDK.

Thanks!

**Comment by OsvaldoRosado** [comment]
Closing as this doesn't look related to this SDK. Please feel free to re-open if this doesn't appear to be the case!
