### ISSUE TITLE
Instrumentation key given, still throwing -"Error: Instrumentation key not found"

### ISSUE THREAD

**Issue by aajahid** [Microsoft/ApplicationInsights-node.js#290]
Following implementation works fine - 

```
var appInsights = require("applicationinsights");
appInsights.setup("<Key>").setAutoDependencyCorrelation(true).start();
```

But when I try to log some exceptions by getting the client as following - 

```
var appInsights = require("applicationinsights");
appInsights.setup("<Key>").setAutoDependencyCorrelation(true).start();
var client = appInsights.getClient();
client.trackException(err);
```
It throws the following error - 

`Error: Instrumentation key not found, pass the key in the config to this method or set the key in the environment variable APPINSIGHTS_INSTRUMENTATIONKEY before starting the server`

I have seen on a different issue that IPv6 support might cause such issue ( #16 ). I'm on Mac OS and it does provide IPv6 when `req.connection.remoteAddress` is being used. I guess my error is also related to that ipv6 issue?

Full Error for debugging - 

```
/Users/aajahid/work/chaldal/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:26
                        throw error;
                        ^
Error: Instrumentation key not found, pass the key in the config to this method or set the key in the environment variable APPINSIGHTS_INSTRUMENTATIONKEY before starting the server
    at new Error (native)
    at Error.AppInsightsAsyncCorrelatedErrorWrapper (/Users/aajahid/work/chaldal/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18) [<root>]
    at Function.Config._getInstrumentationKey (/Users/aajahid/work/chaldal/node_modules/applicationinsights/out/Library/Config.js:45:19) [<root>]
    at new Config (/Users/aajahid/work/chaldal/node_modules/applicationinsights/out/Library/Config.js:7:64) [<root>]
    at new Client (/Users/aajahid/work/chaldal/node_modules/applicationinsights/out/Library/Client.js:22:22) [<root>]
    at Function.ApplicationInsights.getClient (/Users/aajahid/work/chaldal/node_modules/applicationinsights/out/applicationinsights.js:27:16) [<root>]
    at Object.<anonymous> (/Users/aajahid/work/chaldal/build/services/HttpService.js:9:26) [<root>]
    at Module._compile (module.js:570:32) [<root>]
    at Object.Module._extensions..js (module.js:579:10) [<root>]
    at Module.load (module.js:487:32) [<root>]
    at tryModuleLoad (module.js:446:12) [<root>]
    at Function.Module._load (module.js:438:3) [<root>]
    at Module.require (module.js:497:17) [<root>]
    at require (internal/module.js:20:19) [<root>]
```

**Comment by OsvaldoRosado** [comment]
I think the problem here is in using `getClient`. The name is quite confusing for what it does, but hopefully the integrated typings in this SDK should pop up the docs when you try to use it.

`getClient` generates a new client (which gets its own configured instrumentation key). To get the instance of the default client that is configured with `.setup("ikey")` use `appInsights.client`. Alternatively, if you want a new client just use `getClient("ikey")`.

Just like for setup, you can skip providing the ikey in code if it's in the special instrumentation key environment variable.

**Comment by aajahid** [comment]
Ah.. I should have check the implementation before opening up an issue here! Got kind a confused by seeing that other issue - thought I might have similar issue.

Thanks you for your prompt reply, really appreciate it.
