### ISSUE TITLE
Native error is not a constrcutor

### ISSUE THREAD

**Issue by geoffreysamper** [Microsoft/ApplicationInsights-node.js#291]
When installing version 0.21. I get an error onstartup. NativeError is not a constructor. Using node 6.x
```
        //disable these features
        appInsights.setAutoCollectPerformance(false);
        appInsights.setAutoCollectDependencies(false);     
        let appInsightSetup = appInsights.setup(env.appInsights.instrumentationKey); 
```
   When calling method appInsights.setAutoDependencyCorrelation(false); before setup then App insight works

TypeError: NativeError is not a constructor
    at createErrorProperties (/home/geof/github/profiling-tracker-api/node_modules/zone.js/dist/zone-node.js:745:21)
    at /home/geof/github/profiling-tracker-api/node_modules/zone.js/dist/zone-node.js:774:27
    at /home/geof/github/profiling-tracker-api/node_modules/zone.js/dist/zone-node.js:971:3
    at Zone.Zone.zoneSpec._properties (/home/geof/github/profiling-tracker-api/node_modules/zone.js/dist/zone-node.js:9:68)
    at Object.<anonymous> (/home/geof/github/profiling-tracker-api/node_modules/zone.js/dist/zone-node.js:12:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at Module.patchedRequire [as require] (/home/geof/github/profiling-tracker-api/node_modules/diagnostic-channel/.dist/patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Function.CorrelationContextManager.enable (/home/geof/github/profiling-tracker-api/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:75:9)
    at AutoCollectServerRequests.useAutoCorrelation (/home/geof/github/profiling-tracker-api/node_modules/applicationinsights/out/AutoCollection/ServerRequests.js:29:67)
    at Function.ApplicationInsights.start (/home/geof/github/profiling-tracker-api/node_modules/applicationinsights/out/applicationinsights.js:67:49)
    at Object.init (/home/geof/github/profiling-tracker-api/lib/appInsightsUtil.js:17:25)
    at Object.setup (/home/geof/github/profiling-tracker-api/express-setup.js:60:23)
    at Object.<anonymous> (/home/geof/github/profiling-tracker-api/server.js:9:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)

**Comment by OsvaldoRosado** [comment]
Thanks for reporting this!

Are you using any other libraries that patch the Error object? (Or doing it yourself?)

Are you running ’require("applicationinsights")’ as early as possible (ideally before any other requires) like the readme suggests?

**Comment by geoffreysamper** [comment]
@OsvaldoRosado I refactored my code so that app insight is the first require and it works.

**Comment by OsvaldoRosado** [comment]
Thanks! Closing this as it seems fixed. Feel free to re-open if you need to!
