### ISSUE TITLE
Application insights makes process restart every 60 seconds with maximum call stack size exceeded error.

### ISSUE THREAD

**Issue by diprochatterjee** [Microsoft/ApplicationInsights-node.js#294]
RangeError: Maximum call stack size exceeded
    
at AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (src\appName\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:168:28)
    
at NativeError.prepareStackTrace (src\appName\node_modules\zone.js\dist\zone-node.js:900:30)
    
at AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (src\appName\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:168:28)
    
at NativeError.prepareStackTrace (src\appName\node_modules\zone.js\dist\zone-node.js:900:30)
    
at AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (src\appName\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:168:28)
    
at NativeError.prepareStackTrace (src\appName\node_modules\zone.js\dist\zone-node.js:900:30)
    
at AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (src\appName\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:168:28)
    
at NativeError.prepareStackTrace (src\appName\node_modules\zone.js\dist\zone-node.js:900:30)
    
at AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (src\appName\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:168:28)
    
at NativeError.prepareStackTrace (src\appName\node_modules\zone.js\dist\zone-node.js:900:30)
    
at AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (src\appName\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:168:28)
    
at NativeError.prepareStackTrace (src\appName\node_modules\zone.js\dist\zone-node.js:900:30)
   
This happens after a Duplicate key error gets thrown repeatedly which should be ignored in my application. Process restarts because of the above error but does not do it when app insights is not configured.
 Please suggest a solution.

**Comment by diprochatterjee** [comment]
https://github.com/OsvaldoRosado any comments?

**Comment by OsvaldoRosado** [comment]
As a quick mitigation, you may be able to stop this error by using `setAutoDependencyCorrelation(false)` to disable automatic dependency correlation when configuring the SDK.

It looks like there's a problem with the error wrapper that is causing an infinite loop. Are you able to condense this into a small repro code? That would significantly help in root causing this issue

**Comment by diprochatterjee** [comment]
function checkForUpdates (Db1, Db2, queue){
  return Promise.join(
    Db1.getItems(),
    Db2.getItems(),

    (Db1Items, Db2Items)=>{
      let requestItems = Db2Items.filter(sourceItem=>{
        let targetItem = _.find(Db1Items, {Id: sourceItem.ItemId});
        // Update if item does not exist in database 1
        if(!targetItem ) return true;
        // or if have older version than in Datawarehouse(DB2) tables
        return (sourceItem.Serial > targetItem .Serial);
      });

      return Promise.map(requestItems , sourceItem=>{
        let itemId= sourceItem.ItemId;
        return queue.add(itemId)
          .then(added=>{
            log.info(`Item ${itemId} was queued for importing`);
          })
          .catch(err=>{
 // This is the catch block that is throwing the duplicate key error because the items that are added may //already be in the queue and hence being caught here repeatedly. Before I added //insights.trackException, this wasn't a problem but now after a certain number of catches, it crashes with //the error I posted above and restarts the process.
            log.error(err);
            insights.trackException(err);
          });
      });
    });
}

function main(config) {
  log.info(`Connecting to databases....`);
  const start = + new Date;
  return Promise.all([
    DB1.connect(config.Database1),
    DB2.connect(config.Database2),
    queue.connect(config.QueueDB),
  ]).spread((Db1, Db2, queue)=>{
    const done = + new Date;
    const duration = (done - start);
    insights.trackDependency('DB1, DB2', 'connections to DBs', duration, true, 'SQL');
    function doit () {
      insights.setOperationId();
      const startCheckUpdate = + new Date;
      log.info(`Checking updated items in Datawarehouse...Start time =${startCheckUpdate}`);
      checkForUpdates(Db1, Db2, queue)
      .catch(error => {
        log.error(`Error was thrown at ${new Date} while checking for updates. error -> ${JSON.stringify(error)}`);
        insights.trackException(error);
        insights.trackTrace(JSON.stringify(error),'major');
      })
      .finally(()=>{
        const doneCheckUpdate = + new Date;
        const durationCheckUpdate = (doneCheckUpdate - startCheckUpdate);
        log.info(`Done checking for updates = End time = ${doneCheckUpdate}, finished in ${durationCheckUpdate} milliseconds`);
        insights.trackDependency('DB1, DB2', 'CHECK FOR UPDATES', durationCheckUpdate, true, 'SQL');
        log.info(`Updates are being checked at an interval of ${INTERVAL} seconds`);
      });
    }
    setInterval(doit, INTERVAL);
  });
}


if (require.main === module){
  let config = require('./config');
  main(config).catch(err=>{
    log.error(err);
    process.exit(1);
  });
}

**Comment by OsvaldoRosado** [comment]
Looks like its possible for `prepareStackTrace` on the error object to end in an infinite loop if its called multiple times. The wrapper never cleans up its overwrite of `prepareStackTrace` and thus begins to wrap itself infinitely. (See https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/AutoCollection/CorrelationContextManager.ts#L220 which always assumes the stackTrace method it's about to call is not itself)

Out of curiousity, do you stop having this problem if you remove `log.error(err)` before `trackException` ?

**Comment by AlexBulankou** [comment]
@diprochatterjee, would it be possible to get information about the stack frames in the beginning of the stack, so that we know what was the original call to ``.stack`` that triggered the chain of prepareStackTrace calls? Perhaps you could either provide a repro snippet that we could turn into a unit test, or try debugging on your side and put a breakpoint inside ``AppInsightsAsyncCorrelatedErrorWrapper`` to see what triggered the call chain.

**Comment by diprochatterjee** [comment]
I have already provided a snippet of the code that was the cause/zone where the error is coming from. I will try debugging with breakpoints and provide the information to you soon.

**Comment by AlexBulankou** [comment]
Thanks @diprochatterjee. In your snippet, do you happen to know which call is causing the start of prepareStackTrace() chain? There are quite a few ones that can potentially call .stack internally. Also if you could reduce your snippet to a runnable one that would be great. Thanks so much for helping us here.

**Comment by AlexBulankou** [comment]
Moving out of 0.22 release as we don't have a repro right now.

**Comment by dmytro-lymarenko** [comment]
I got such error on v1.0.4 :(

**Comment by OsvaldoRosado** [comment]
@dmytro-lymarenko Can you provide a code sample that reproduces the problem? Is your call stack the same as the one quoted in the issue description?

**Comment by johannordin** [comment]
I got problems when i initiated (`appInsights.setup(..)....`) to early, now I'm initiating when my express app has booted, seems to work atm.

**Comment by christianrondeau** [comment]
I have the issue intermittently, and only at startup. The application crashes with this error. Restarting it will usually solve the problem for some time, which makes it impossible to reproduce in a smaller project.

It seems to fail even without initializing first when the library is imported.

I'm using 1.0.7.

There might be another root cause external to AI but I can't really tell... 

Might I suggest, since we know it happens in a few different cases, to count recursive errors and after 10 iterations, log an error saying the log was dropped and let the error bubble up? I guess we won't be able to easily reproduce the root cause(s) but at least when it happens it won't bring everything down with it! 

What do you think? Should this be reopened?
