### ISSUE TITLE
Receiving "Zone already loaded" error when requiring AI client in Function App

### ISSUE THREAD

**Issue by willmorgan** [Microsoft/ApplicationInsights-node.js#346]
Using applicationinsights@1.0.0 I am receiving this error, which causes the function to fail and respond 500:

```
2017-10-25T14:58:03.588 Exception while executing function: Functions.di-session-update
2017-10-25T14:58:03.588 Error: Zone already loaded.
    at new Error (native)
    at D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:25:15 [<root>]
    at D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:971:3 [<root>]
    at Zone.Zone.zoneSpec._properties (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:9:68)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:12:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/module.js:20:19)
2017-10-25T14:58:03.588 Function completed (Failure, Id=9b458b5a-010e-4bbf-adaa-3616ea3de4b7, Duration=28ms)
2017-10-25T14:58:03.588 Executed 'Functions.di-session-update' (Failed, Id=9b458b5a-010e-4bbf-adaa-3616ea3de4b7)
```

This isn't an issue for my other function which is part of the function app.

My functions currently share a package.json file between them, and I configure the ApplicationInsights client inside some shared library code, so I wonder if there's something happening here which might cause the module to be included twice:

```js
const appInsights = require('applicationinsights');
function setupInsights() {
    /* omitted dev-only code which skips setup if process.env.NODE_ENV is dev */
    appInsights.setup()
        .setAutoCollectConsole(true, true) // Enable logging of all console methods.
        .start();
    return appInsights;
}

module.exports = setupInsights();

```

I had a look in CorrelationContextManager.js to see where it's being required, but I'm not doing anything too special.

**Comment by OsvaldoRosado** [comment]
Are there other libraries in your project that use zone.js? That would potentially cause this error.

Easiest workaround is to disable the automatic dependency correlation feature if you don’t need it. You can do that by adding ‘setAutoDependencyCorrelation(false)’ after your ‘setAutoCollectConsole’ command.

**Comment by willmorgan** [comment]
Hi @OsvaldoRosado, thanks for jumping on this so quickly.

I've run `npm ls zones.js` and I just see `applicationinsights` being the only consumer of that library so I'm confident we aren't doing anything strange.

**Comment by OsvaldoRosado** [comment]
As a quick test, if you place a console log in your `setupInsights` method, do you see it repeated twice in your failing Function? This would imply we have a bug when `setup()` is called twice.

**Comment by christopheranderson** [comment]
Azure Functions will load both of your Functions into the same Node.js process. If somehow each Function is triggering the zone.js load code path, that might impact it.

**Comment by willmorgan** [comment]
> As a quick test, if you place a console log in your setupInsights method, do you see it repeated twice in your failing Function? This would imply we have a bug when setup() is called twice.

I see only one occurrence of it on my local runtime.

> Azure Functions will load both of your Functions into the same Node.js process. If somehow each Function is triggering the zone.js load code path, that might impact it.

`setupInsights` is called once. Unless there is some weirdness happening where the require result is not cached between functions, I don't think that's what's going on here.

**Comment by willmorgan** [comment]
As an aside, when deployed on Azure, as `setupInsights` is called outside the scope of a request or trigger, I have no opportunity to do `context.log` so I cannot see what is happening.

I have tried using `console.log` and `process.stdout.write` to see if the output is captured in the log files. So far I have been unable to locate my debug output using the log features Kudu provides us. Am I looking in the wrong place?

Does anyone have any pointers for this? I have already reported this issue to Microsoft but the response has been to use ApplicationInsights. As we're trying to debug ApplicationInsights before it's even initialised, I'm a little stumped.

**Comment by martinpeck** [comment]
@willmorgan can you confirm that you're putting the instrumentation key into the `APPINSIGHTS_INSTRUMENTATIONKEY` env variable?

If so....I suspect the issue you're seeing is because Azure Functions sets up Application Insights for you (and calls `setup`). 

If you look at this...

https://github.com/Azure/Azure-Functions/wiki/App-Insights

... you can see that all you need to do it add the environment variable, and Functions "does the rest".

**Comment by martinpeck** [comment]
Check out the Node.js instructions at the bottom of this page: https://github.com/Azure/Azure-Functions/wiki/App-Insights#nodejs-experience

Also, the example here: https://github.com/christopheranderson/azure-functions-app-insights-sample/blob/master/process-item/index.js

**Comment by willmorgan** [comment]
So, following @martinpeck's suggestion I had a play around with conditionally setting up the `applicationinsights` client if defaultClient exists.

This still seems to track things on Azure, on our local environment, and complains accordingly if no insights key is set and we're running in anything other than development:

```js
const appInsights = require('applicationinsights');

function setupInsights() {
    if (!process.env.APPINSIGHTS_INSTRUMENTATIONKEY && process.env.NODE_ENV === 'development') {
        const logger = console;
        process.stderr.write('Skipping app insights setup - in development mode with no ikey set\n');
        return {
            defaultClient: {
                trackEvent: logger.log.bind(console, 'trackEvent'),
                trackException: logger.error.bind(console, 'trackException'),
                trackMetric: logger.log.bind(console, 'trackMetric'),
            },
        };
    } else if (process.env.APPINSIGHTS_INSTRUMENTATIONKEY) {
        if (!appInsights.defaultClient) {
            appInsights.setup();
            process.stdout.write('No app insights setup - performing manual setup\n');
        } else {
            process.stdout.write('App insights setup - client already detected\n');
        }
        process.stdout.write('App insights setup - configuring client\n');
        appInsights.start().setAutoCollectConsole(true, true);
    } else {
        throw new Error('No app insights setup. A key must be specified in non-development environments.');
    }
    return appInsights;
}

module.exports = setupInsights();
```

**Comment by OsvaldoRosado** [comment]
> As for the AppInsights library, is it possible to avoid requiring zones twice if we already have a defaultClient (or if appInsights.setup() has already been called?)

Labeling as bug to track this. The intended behavior is a bit more nuanced than you've described. The intended logic is that require is called once during initialization of the autocorrelation feature. (Eg. it's required at the time of `start()` if correlation is enabled, or at the time of enabling correlation if start was already called in the past). This means it's definitely a valid scenario for the require to happen after defaultClient exists or setup has been called. There's already logic in place that is supposed to prevent the require from happening more than once, the bug for this is to verify it's working correctly.

**Comment by willmorgan** [comment]
That sounds perfect. Thanks, @OsvaldoRosado.

**Comment by jem-Solytica** [comment]
I also experience this issue while trying to use application insights to add custom events/metrics from an Azure function. The issue seems to manifest whenever a code change occurs (continuous deploy from VSTS to functions app, or by overwriting the function from within the Azure portal). It resolves by restarting the function app from within the portal. Here is the snip from the function where I initialize appInsights, and where I see the error:

```
const appInsights = require('applicationinsights');
appInsights.setup(process.env['APPINSIGHTS_INSTRUMENTATIONKEY']).start();
const aiClient = appInsights.defaultClient;
```

If I remove (comment-out) the third line (with the setup().start()), I don't see the error, and my metrics still seem to post fine.

**Comment by willmorgan** [comment]
I've worked around this issue by simply not setting `APPINSIGHTS_INSTRUMENTATIONKEY` in my function app.

Instead I set my own environment variable and manually configure app insights.

This way I don't need to worry about Function App lifecycles.

**Comment by jem-Solytica** [comment]
@willmorgan — I tried that as well, but did not have any luck. I thought it was related to having more than one function in the app using app insights, but it’s not—I see the same error even when I only have one function in an app.

**Comment by OsvaldoRosado** [comment]
@jem-Solytica Does guarding the call to `start()` resolve this for you? Eg.:

```
if (!appInsights.defaultClient) {
   appInsights.setup();
}
```

**Comment by jem-Solytica** [comment]
@OsvaldoRosado -- No, unfortunately it does not. Here's a code sample of the latest iteration I've tried. This particular function is configured to use an httpTrigger and httpOutput. I've also tried moving the appInsights code right after the ```'use strict';``` clause, and declaring them as variations of ```const``` and ```var```. In the case below, I can cause the error by editing the function to comment/uncomment the ```aiClient.trackEvent()``` line, saving the code, and running the function. Does not seem to matter whether I edit in the Azure Portal (or through source control, but the portal is most convenient).

```
/*
 * File: index.js
 * Function: appInTesting
 */
'use strict';

const opId = "appInTesting";
const funcVer = "1801.1";
const logVerbose = ( process.env['doLogVerbose'] === 'true' ) ? true : false;
var context;  //make this a global variable

/**
 * Set the result binding to show a friendly message.
 * 
 * logMsg - what message to write to the log
 * showErrToUser - bool, context.done(msg) if true
 */
function bindErrAndDone(logMsg, showErrToUser) {
  context.bindings.res = {
    status: 500,
    body: '<!DOCTYPE html><html><head><title>Offline</title></head><body>An unknown application error occurred. Status updates at <a href="https://OMITTED">https://OMITTED</a>. If this issue has not been previously reported, please contact support@OMITTED and report Correlation ID: ' + context.invocationId + '</body></html>',
    headers: {
      'Content-Type': 'text/html',
      'x-wc-correlationId': context.invocationId
    }
  };
  context.log.error(logMsg);
  if (showErrToUser) {
    context.done(logMsg);
  } else {
    context.done();
  }
}

/**
 * This code is the entry point when invoking the Azure Function.
 */
function AppInTesting(txetnoc) {
  context=txetnoc;  //move the context global
  let cDonePref = opId + "_" + context.invocationId + ' :: ';
  
  // Setup App Insights
  let aiClient;
  let appInsights;
  try {
    if ( typeof process.env['custom_APPINSIGHTS_INSTRUMENTATIONKEY'] != 'undefined' && process.env['custom_APPINSIGHTS_INSTRUMENTATIONKEY'] !== null ) {
      appInsights = require('applicationinsights');
      if (!appInsights.defaultClient)
        appInsights.setup(process.env['custom_APPINSIGHTS_INSTRUMENTATIONKEY']).start();
      aiClient = appInsights.defaultClient;
    }
  } catch (err) {
    bindErrAndDone('An error occurred while setting up application insights.Error:\n' + err.message, false); return;
  }

  let aiTagOverrides = { 
    'ai.cloud.role': 'fApp-ApplicationName' ,
    'ai.operation.id': context.invocationId
  }; //set the cloud role for custom app insights

  aiClient.trackEvent({ name: "CustomEvent Confirmed", tagOverrides: aiTagOverrides });

  /* Business Logic Omitted */
  
  context.done();
}

module.exports = AppInTesting;
```

**Comment by OsvaldoRosado** [comment]
@jem-Solytica Just to be clear. Are you getting an error when calling `trackEvent` or when calling `start`? If it's on `trackEvent`, can you provide a stack trace? That might be a different error than what's originally reported here.

Anther fix, specifically for Functions as I don't believe this feature does anything within Functions anyway, is to add `.setAutoDependencyCorrelation(false)` to the `.setup` chain

**Comment by jem-Solytica** [comment]
@OsvaldoRosado Yes, the error was occurring during setup. And, the inserting ```.setAutoDependencyCorrelation(false)``` does seems to resolve the issue. I'll try it on some of the other functions I'm using, but I'm afraid of what I'll loose, especially on some of my more complex functions that do have a lot of dependencies. And, the documentation _clearly_ says to keep it enable it, so it must do something, right? (Ref: [Application Insights Documentation](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs), search for "setAutoDependencyCorrelation")

**Comment by OsvaldoRosado** [comment]
This method ties dependency events to request events via `operation_Id`. However, in the Azure Functions environment, `trackRequest` is never called (as your Node code doesn't itself run the HTTP server) - thus making automatic dependency correlation essentially a no-op in this edge case.

**Comment by willmorgan** [comment]
@OsvaldoRosado Thanks - I'll update and give it a go.
