### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by digeff** [Microsoft/ApplicationInsights-node.js#362]
We get this exception sometimes which might be related to this line https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/AutoCollection/CorrelationContextManager.ts#L206  and to having stack traces without filenames.

    TypeError: Cannot read property 'indexOf' of null
        at Function.AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:155:47)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at Function.NativeError.prepareStackTrace (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/zone.js/dist/zone-node.js:900:30)
        at formatError (util.js:642:16)
        at formatValue (util.js:543:16)
        at inspect (util.js:324:10)
        at Logger.format (util.js:253:18)
        at mkRecord (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/bunyan/lib/bunyan.js:984:22)
        at Logger.error (/opt/logpoints-agent/node_modules/logpoints-agent/node_modules/bunyan/lib/bunyan.js:1044:19)
        at Routes.<anonymous> (/opt/logpoints-agent/node_modules/logpoints-agent/dist/src/routes/routes.js:88:33)

**Comment by OsvaldoRosado** [comment]
Thanks for reporting this!

**Comment by jlawrencecfm** [comment]
We are also experiencing this issue, here's the stacktrace recorded by application analytics:

Method | File | Line
-------|------|-----
Function.AppInsightsAsyncCorrelatedErrorWrapper.orig.prepareStackTrace | CorrelationContextManager.js | 155
Function.NativeError.prepareStackTrace | zone-node.js | 900
Console.trace | console.js | 83
Console.originalConsole.(anonymous function) [as trace] | console.pub.js | 42
Socket.addListener [as __zone_symbol__addListener] | events.js | 239
Object.invokeAddFunc | zone-node.js | 1065
ZoneTask.scheduleEventListener [as scheduleFn] | zone-node.js | 1092
ZoneDelegate.scheduleTask | zone-node.js | 255
Zone.scheduleEventTask | zone-node.js | 171
zoneAwareAddListener | zone-node.js | 1137
<no_method> | zone-node.js | 1266
Socket.addListener (eval at createNamedFn | zone-node.js:1:0), <anonymous> | 3
module.exports.join | taskActivity.js | 15
Socket.<anonymous> (/home/cloudfmadmin/apps/nodePortal/node_modules/ | index.js | 261
ZoneDelegate.invokeTask | zone-node.js | 275
Zone.runTask | zone-node.js | 151
Socket.ZoneTask.invoke | zone-node.js | 345
emitOne | events.js | 77
Socket.emit | events.js | 169
SocketNamespace.handlePacket | namespace.js | 335
Manager.onClientMessage | manager.js | 518
WebSocket.Transport.onMessage | transport.js | 369
Parser.<anonymous> | hybi-16.js | 39
ZoneDelegate.invokeTask | zone-node.js | 275
Zone.runTask | zone-node.js | 151
Parser.ZoneTask.invoke | zone-node.js | 345
emitOne | events.js | 77
Parser.emit | events.js | 169
finish | hybi-16.js | 295
Parser.expectHandler | hybi-16.js | 306
Parser.add | hybi-16.js | 482
Parser.expect | hybi-16.js | 519
Parser.<anonymous> | hybi-16.js | 305
Parser.add | hybi-16.js | 482
Parser.expect | hybi-16.js | 519
expectData | hybi-16.js | 303
Parser.<anonymous> | hybi-16.js | 324
Parser.add | hybi-16.js | 482
Parser.expect | hybi-16.js | 519
Parser.opcodeHandlers.1 | hybi-16.js | 323

**Comment by OsvaldoRosado** [comment]
Thanks for reporting your additional repro! Until a new SDK version is released with extra guards around missing file names in stack frames, you can work around this by disabling automatic correlation with `setAutoDependencyCorrelation(false)`

**Comment by OsvaldoRosado** [comment]
This should be fixed now in 1.0.2. Please reopen if you're still seeing this!
