### ISSUE TITLE
ECONNRESET for NodeJS Web Apps using ApplicationInsights module

### ISSUE THREAD

**Issue by mredison** [Microsoft/ApplicationInsights-node.js#377]
Hi all, we are experiencing some random errors occurring in Application Insights module with the following description:

{ Error: read ECONNRESET
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:811:33)
    at AppInsightsAsyncCorrelatedErrorWrapper (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193:18)
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:582:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

I have searched that this can be related to idle time request that is closed by the server after some minutes. 
We are not getting these errors in other methods/packages just in this module. Any idea?

Thanks

**Comment by OsvaldoRosado** [comment]
These two lines at the top of the stack are simply because we wrap error handlers, rather than being the root cause of the error itself. Do you still see this error even with this SDK disabled?

**Comment by mredison** [comment]
Hi Osvaldo, thanks for your quick response. Let me try that. Thanks

**Comment by ThomasKruegl** [comment]
Maybe it would be worth to document this somewhere (or did i miss it?)

I also wondered where those "AppInsightsAsyncCorrelatedErrorWrapper" stuff in some Errors was coming from, figured out that it was because of the wrapping.

**Comment by OsvaldoRosado** [comment]
@ThomasKruegl Good idea about documenting.

This also isn't fully intended. The error wrapper has code to remove itself from the stack trace (to avoid confusion like this), but it looks like this doesn't work all of the time

**Comment by mredison** [comment]
Hi Osvaldo my customer upgraded the client to this version 1.0.2 and it seems to work, he is not getting these errors anymore. Thanks

**Comment by enlivenaman** [comment]
Hi all i am facing below random issue, and don't have idea what to do please suggest solution for same

ApplicationInsights:Sender [ { Error: read ECONNRESET
      at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\inetpub\wwwroot\node_modules\zone.js\dist\zone-node.js:811:33)
      at AppInsightsAsyncCorrelatedErrorWrapper (C:\inetpub\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
      at exports._errnoException (util.js:1050:11)
      at TLSWrap.onread (net.js:582:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } ]
ApplicationInsights:Sender [ { Error: self signed certificate in certificate chain
      at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
      at ZoneDelegate.invokeTask (C:\inetpub\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
      at Zone.runTask (C:\inetpub\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
      at TLSSocket.ZoneTask.invoke (C:\inetpub\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:188:7)
      at TLSSocket._finishInit (_tls_wrap.js:610:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' } ]

**Comment by enlivenaman** [comment]
@mredison I m alresdy using v7.10.0

**Comment by OsvaldoRosado** [comment]
@enlivenaman Could you make a new issue for this? I don't believe this is the same as this issue. This issue was over ECONNRESET being fired in user code and a merely confusing stack that made it look like an SDK issue, but yours is ECONNRESET being fired from the SDK itself.

Your issue is closer to #180. Perhaps in newer node the error message changed from `UNABLE_TO_VERIFY_LEAF_SIGNATURE` to `SELF_SIGNED_CERT_IN_CHAIN` - though I find that to be unlikely. More suspicious would be running the SDK behind some kind of proxy that is re-signing SSL certificates - causing this SDK to complain that the Application Insights backend appears to be untrusted.

**Comment by enlivenaman** [comment]
hi @OsvaldoRosado  i have created issue #389 for this

**Comment by kazlauskis** [comment]
Same here, using applicationinsights v1.0.2, Node 8.9.1:

`ApplicationInsights:Sender [ { Error: read ECONNRESET
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/opt/node_modules/zone.js/dist/zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (/opt/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } ]`
