### ISSUE TITLE
ECONNRESET and SELF_SIGNED_CERT_IN_CHAIN issue

### ISSUE THREAD

**Issue by enlivenaman** [Microsoft/ApplicationInsights-node.js#389]
Hi all i am facing below random issue, and don't have idea what to do please suggest solution for same

ApplicationInsights:Sender [ { Error: read ECONNRESET
at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\inetpub\wwwroot\node_modules\zone.js\dist\zone-node.js:811:33)
at AppInsightsAsyncCorrelatedErrorWrapper (C:\inetpub\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
at exports._errnoException (util.js:1050:11)
at TLSWrap.onread (net.js:582:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } ]
ApplicationInsights:Sender [ { Error: self signed certificate in certificate chain
at TLSSocket. (_tls_wrap.js:1088:38)
at ZoneDelegate.invokeTask (C:\inetpub\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
at Zone.runTask (C:\inetpub\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
at TLSSocket.ZoneTask.invoke (C:\inetpub\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:188:7)
at TLSSocket._finishInit (_tls_wrap.js:610:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' } ]

**Comment by OsvaldoRosado** [comment]
Thanks for making the new issue! Can you confirm if your Node server is behind any kind of proxy (or other kinds of interception at the network layer). In particular anything that would re-sign SSL certificates? This error seems to imply our backend's SSL certificate is being replaced by a self-signed one in a man-in-the-middle fashion.

Does this error happen all the time, or only occasionally?

**Comment by enlivenaman** [comment]
Yes @OsvaldoRosado It happens only when I run my node server behind proxy, else for open network it works fine. So, every time when I run my node sever I need to make switch from my organisation proxy network to open network. Is there any way out to run my node server behind proxy?
And to answer your question I'm not using any custom `endpointUrl`

**Comment by OsvaldoRosado** [comment]
The issue here isn't necessarily about running behind a proxy, but that your proxy is signing requests with an untrusted (to Node at least) SSL certificate. If you can't change the proxy's certificate you can try to configure Node to trust your self-signed cert.

This related stackoverflow answer might help: https://stackoverflow.com/a/47160447 (or **far** less secure but easier https://stackoverflow.com/a/21961005 )

**Comment by OsvaldoRosado** [comment]
In the just-released 1.0.3 you can also specify a custom https.Agent (https://nodejs.org/api/https.html#https_class_https_agent) to use for outgoing requests. For this scenario, you could provide an agent that trusts your self-signed certificate.

**Comment by OsvaldoRosado** [comment]
Closing this. Feel free to re-open if you have more questions!
