### ISSUE TITLE
Error with puppeteer: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by spike008t** [Microsoft/ApplicationInsights-node.js#406]
I'm facing this issue when using puppeteer (v1.5.0 at the moment) with the latest version of ApplicationInsights-node.js

When calling:

```js
const browser = await puppeteer.launch();
```

I do have the following error:

```
Unhandled Promise rejection: Cannot read property 'protocol' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'protocol' of undefined
    at Function.HttpDependencyParser._getUrlFromRequestOptions (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencyParser.js:135:62)
    at new HttpDependencyParser (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencyParser.js:28:46)
    at Function.AutoCollectHttpDependencies.trackRequest (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:105:29)
    at clientRequestPatch (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:46:45)
    at Object.AutoCollectHttpDependencies._initialize.http.request (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:59:13)
    at Object.AutoCollectHttpDependencies._initialize.http.get (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:80:52)
    at WebSocket.initAsClient (/src/node_modules/puppeteer/node_modules/ws/lib/websocket.js:522:33)
    at new WebSocket (/src/node_modules/puppeteer/node_modules/ws/lib/websocket.js:62:20)
    at EventEmitter.createForWebSocket.Promise (/src/node_modules/puppeteer/lib/Connection.js:32:18)
    at new ZoneAwarePromise (/src/node_modules/zone.js/dist/zone-node.js:551:29)
    at Function.createForWebSocket (/src/node_modules/puppeteer/lib/Connection.js:31:12)
    at Function.launch (/src/node_modules/puppeteer/lib/Launcher.js:163:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) TypeError: Cannot read property 'protocol' of undefined
    at Function.HttpDependencyParser._getUrlFromRequestOptions (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencyParser.js:135:62)
    at new HttpDependencyParser (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencyParser.js:28:46)
    at Function.AutoCollectHttpDependencies.trackRequest (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:105:29)
    at clientRequestPatch (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:46:45)
    at Object.AutoCollectHttpDependencies._initialize.http.request (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:59:13)
    at Object.AutoCollectHttpDependencies._initialize.http.get (/src/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:80:52)
    at WebSocket.initAsClient (/src/node_modules/puppeteer/node_modules/ws/lib/websocket.js:522:33)
    at new WebSocket (/src/node_modules/puppeteer/node_modules/ws/lib/websocket.js:62:20)
    at EventEmitter.createForWebSocket.Promise (/src/node_modules/puppeteer/lib/Connection.js:32:18)
    at new ZoneAwarePromise (/src/node_modules/zone.js/dist/zone-node.js:551:29)
    at Function.createForWebSocket (/src/node_modules/puppeteer/lib/Connection.js:31:12)
    at Function.launch (/src/node_modules/puppeteer/lib/Launcher.js:163:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

The issue is puppeteer setup a websocket without agent and the protocol is set to `undefined` as we can see If I dump the the parameters passed on `HttpDependencyParser` constructor : 

```
requestOptions={ protocolVersion: 13,
  perMessageDeflate: false,
  createConnection: [Function: netConnect],
  socketPath: undefined,
  hostname: undefined,
  protocol: undefined,
  timeout: undefined,
  method: undefined,
  auth: undefined,
  host: '127.0.0.1',
  path: '/devtools/browser/6492d106-2128-4d03-a652-15150f5678ac',
  port: '55890',
  headers:
   { 'Sec-WebSocket-Version': 13,
     'Sec-WebSocket-Key': 'vVxZ++WSsHucfp7lswdZYw==',
     Connection: 'Upgrade',
     Upgrade: 'websocket' } }
request=ClientRequest {
  domain: null,
  _events: { socket: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  output: [],
  outputEncodings: [],
  outputCallbacks: [],
  outputSize: 0,
  writable: true,
  _last: true,
  upgrading: false,
  chunkedEncoding: false,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: false,
  sendDate: false,
  _removedConnection: false,
  _removedContLen: false,
  _removedTE: false,
  _contentLength: null,
  _hasBody: true,
  _trailer: '',
  finished: false,
  _headerSent: false,
  socket: null,
  connection: null,
  _header: null,
  _onPendingData: [Function: noopPendingOutput],
  agent: undefined,
  socketPath: undefined,
  timeout: undefined,
  method: 'GET',
  path: '/devtools/browser/6492d106-2128-4d03-a652-15150f5678ac',
  _ended: false,
  res: null,
  aborted: undefined,
  timeoutCb: null,
  upgradeOrConnect: false,
  parser: null,
  maxHeadersCount: null,
```

I don't know if that issue should be fixed here or on puppeteer/websocket. But looks like that `protocol` can be null

BTW I provide a "simple" patch to make it works see PR 407.

**Comment by OsvaldoRosado** [comment]
Closing as fixed by #407

Thanks for the fix!
