### ISSUE TITLE
AutoCollection Exception

### ISSUE THREAD

**Issue by skazanskiy3** [Microsoft/ApplicationInsights-node.js#411]
Getting an exception from AutoCollection

*****/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:33
                        throw error;
                        ^
Error: The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:562d6b5928794a8691e30a807357c468_G30, SystemTracker:gateway5, Timestamp:7/12/2018 1:58:58 AM
    at Sender.link.on_detach (******/node_modules/rhea/lib/link.js:159:86)
    at Session.on_detach (******/node_modules/rhea/lib/session.js:668:27)
    at Connection.(anonymous function) [as on_detach] (******/node_modules/rhea/lib/connection.js:671:30)
    at c.dispatch (******/node_modules/rhea/lib/types.js:904:33)
    at Transport.read (******/node_modules/rhea/lib/transport.js:95:36)
    at SaslClient.read (******/node_modules/rhea/lib/sasl.js:277:26)
    at Connection.input (******/node_modules/rhea/lib/connection.js:428:35)
    at ZoneDelegate.invokeTask (******/node_modules/zone.js/dist/zone-node.js:275:35)
    at Zone.runTask (******/node_modules/zone.js/dist/zone-node.js:151:47)
    at TLSSocket.ZoneTask.invoke (******/node_modules/zone.js/dist/zone-node.js:345:33)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
[2018-07-11T21:58:58.250] [INFO] - closed child_process:7
[2018-07-11T21:58:58.413] [ERROR] - processing status: error message: Processing error code: 7

**Comment by OsvaldoRosado** [comment]
This exception isn't actually from AutoCollection (or this SDK). This is actually an uncaught exception from somewhere else in your application. This SDK has an uncaught exception handler to automatically collect telemetry on uncaught exceptions before they crash your app. To ensure the SDK doesn't impact app behavior (vs what would happen if this SDK did not catch the otherwise uncaught exception), it re-throws it.

If you are interested, the code from AutoCollection relevant here can be found at: https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/AutoCollection/Exceptions.ts#L42

For a next step I would look at the next line of the stack trace, `/node_modules/rhea/lib/link.js:159:86`
