### ISSUE TITLE
ApplicaitonInsights breaking S3 uploads over 1mb

### ISSUE THREAD

**Issue by BCook98** [microsoft/ApplicationInsights-node.js#516]
We are seeing the exception below in our environments when attempting to upload files to S3 larger than 1ish mb. 

See https://github.com/BCook98/aws-sdk-application-insights for a complete reproducible example.

Node: v9 - v12
AWS SDK: v2.48.0 - v2.452.0
Application Insights: v1.3.1

For the time being as a workaround we have disabled tracking on s3 domains using the below code. However we would like to have this information tracked.
```js
appInsights.defaultClient.config.correlationHeaderExcludedDomains = ['*.s3.amazonaws.com'];
```

Please let me know if you need any additional information to help resolve this issue.

**Exception**
```
{ NetworkingError: Cannot set headers after they are sent to the client
    at ClientRequest.setHeader (_http_outgoing.js:470:11)
    at Function.AutoCollectHttpDependencies.trackRequest (/Users/brandon/s3-application-insights/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:122:39)
    at clientRequestPatch (/Users/brandon/s3-application-insights/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:45:45)
    at Object.https.request (/Users/brandon/s3-application-insights/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:67:13)
    at features.constructor.handleRequest (/Users/brandon/s3-application-insights/node_modules/aws-sdk/lib/http/node.js:42:23)
    at executeSend (/Users/brandon/s3-application-insights/node_modules/aws-sdk/lib/event_listeners.js:342:29)
    at Request.SEND (/Users/brandon/s3-application-insights/node_modules/aws-sdk/lib/event_listeners.js:356:9)
    at Request.callListeners (/Users/brandon/s3-application-insights/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/Users/brandon/s3-application-insights/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/brandon/s3-application-insights/node_modules/aws-sdk/lib/request.js:683:14)
  message: 'Cannot set headers after they are sent to the client',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 's3.amazonaws.com',
  retryable: true,
  time: 2019-05-14T00:52:36.693Z }
/Users/brandon/s3-application-insights/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:34
                        throw THIS_IS_APPLICATION_INSIGHTS_RETHROWING_YOUR_EXCEPTION; // Error originated somewhere else in your app
                        ^

TypeError: Cannot read property 'didCallback' of undefined
    at ClientRequest.<anonymous> (/Users/brandon/s3-application-insights/node_modules/aws-sdk/lib/http/node.js:43:18)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at ClientRequest.emitted (/Users/brandon/s3-application-insights/node_modules/emitter-listener/listener.js:134:21)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
```

**Comment by OsvaldoRosado** [comment]
Thanks for opening this issue!

Can you expand more on why adding s3 to the header modification blacklist isn’t an ideal solution for your use case? Are you relying on reading those headers from the s3 side?

**Comment by BCook98** [comment]
My bad, my assumption was that by adding it to the blacklist it would also exclude not track the http dependency. I just double checked and that isn't the case.

It still isn't ideal to have to have to hardcode this in our current and future applications that use s3.

**Comment by OsvaldoRosado** [comment]
Got it. Thanks!

Looks like this needs some investigation into why our header adding is happening late in this circumstance. This blacklist is meant to fix servers who don’t work with our headers - not to avoid crashes - so it’s definitely not a long term solution for this specific problem.

Regardless of root cause, we should also probably try catch around the header modification to protect against this exception when it does happen.

**Comment by markwolff** [comment]
Wrapped our setHeader calls in a try/catch, so the crash should be resolved. Will add a proper RCA to backlog, since correlation will be dropped when setHeader failed. However, no correlation is really possible with S3 since they do not parse AI headers. They made parse W3C headers in the future though...
