### ISSUE TITLE
`define is not defined` when trying to run inside Jest

### ISSUE THREAD

**Issue by dotansimha** [microsoft/ApplicationInsights-node.js#547]
While trying to run Jest tests, I'm getting the following error:

```
    ReferenceError: define is not defined

      at Object.<anonymous> (../../node_modules/append-field/bundle/ai.module.js:215:1)
      at Object.<anonymous> (../../node_modules/multer/lib/make-middleware.js:5:19)

```

The actual `ai.module` file points to the following code (`node_modules/append-field/bundle/ai.module.js`):
![image](https://user-images.githubusercontent.com/3680083/64484658-3b76bd00-d21e-11e9-866a-43dece050bf7.png)

While running in regular NodeJS, everything seems fine, it happens only with Jest runner. 

Adding the following line in my test file seems to workaround this: 

```
global['define'] = () => null;
```

Tested with 1.4.1 and 1.4.2. 
NodeJS 10/12
Jest 24.9.0 with ts-jest

**Comment by dotansimha** [comment]
Actually, it happens also with TypeScript CommonJS environment (tested Node 10/12 with latest TypeScript). 

```
ReferenceError: define is not defined
    at Object.<anonymous> (/Users/dotansimha/Dev/WebApp/node_modules/append-field/bundle/ai.module.js:215:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module._compile (/Users/dotansimha/Dev/WebApp/packages/api/node_modules/source-map-support/source-map-support.js:521:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.nodeDevHook [as .js] (/Users/dotansimha/Dev/WebApp/packages/api/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at Module.patchedRequire [as require] (/Users/dotansimha/Dev/WebApp/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by markwolff** [comment]
It looks like you are using the JS SDK (https://github.com/microsoft/applicationinsights-js), which was packaged with AMD AFAIK. Your workaround is fine, since it only impacts tests, but you can try upgrading to the latest package name on that repo. It is instead packaged as UMD, which should be "universally" compat
