### ISSUE TITLE
Error: Cannot find module './routes/tools/status'

### ISSUE THREAD

**Issue by JoeEarly** [microsoft/ApplicationInsights-node.js#548]
Just pulled my source down from our repo after a machine rebuild and now getting the above error after running npm install. 

has something changed recently as I have this code running in 2 live instances without the error 

`node server.js

/Users/joeearly/Documents/GitHub/fishpal_iisnode/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:33
                        throw error;
                        ^
Error: Cannot find module './routes/tools/status'
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/Users/joeearly/Documents/GitHub/fishpal_iisnode/node_modules/zone.js/dist/zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (/Users/joeearly/Documents/GitHub/fishpal_iisnode/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:193:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.patchedRequire [as require] (/Users/joeearly/Documents/GitHub/fishpal_iisnode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/cccccc/Documents/GitHub/fishpal_iisnode/server.js:57:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)`

**Comment by markwolff** [comment]
It looks like you are using an older version of the SDK which used zone.js. We've since deprecated this dependency in favor of cls-hooked, which resolved pretty much all of these types of cryptic errors. Try updating to the latest version and let me know how it goes.

**Comment by JoeEarly** [comment]
Yea was vr1 still, so updated to 1.4.2 and the error is still present a bit a little different 

/Users/joeearly/Documents/GitHub/fishpal_iisnode/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:34
                        throw THIS_IS_APPLICATION_INSIGHTS_RETHROWING_YOUR_EXCEPTION; // Error originated somewhere else in your app
                        ^

Error: Cannot find module './routes/tools/status'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.patchedRequire [as require] (/Users/joeearly/Documents/GitHub/fishpal_iisnode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/joeearly/Documents/GitHub/fishpal_iisnode/server.js:57:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by markwolff** [comment]
Does `./routes/tools/status` exist in your app? This SDK adds a global uncaught error handler which rethrows (and crashes your app, as it would without it) any errors it receives. If you have an existing uncaught error handler that swallows errors instead of crashing, then this SDK is probably overriding that handler.

This doesn't look like an error caused by this SDK though, and that file is not something this SDK knows about.

**Comment by JoeEarly** [comment]
My bad, was indeed an uncaught error from me and the AI catching it was throwing me off. 

Thank Mark for your time
