### ISSUE TITLE
TrackDependency update is breaking the code.

### ISSUE THREAD

**Issue by utkarsh-globant** [microsoft/ApplicationInsights-node.js#594]
After updating the applicationinsights dependency version to 1.7.2, the **track dependency** code is breaking. It is working fine with 1.4.2 version..

I have found that, the **telemetry name** is optional, and previously we were just logging it without caring about it length and all.. But in the updated version(1.7.2), we are trying to find the "length" property of the name, and if it is undefined, it is breaking the code.

**Stack Trace:**

**"TypeError: Cannot read property 'length' of undefined**
    at Function.EnvelopeFactory.createDependencyData (C:\test\node_modules\applicationinsights\out\Library\EnvelopeFactory.js:100:48)
    at Function.EnvelopeFactory.createEnvelope (C:\test\node_modules\applicationinsights\out\Library\EnvelopeFactory.js:26:40)
    at NodeClient.TelemetryClient.track (C:\test\node_modules\applicationinsights\out\Library\TelemetryClient.js:109:44)
    at NodeClient.TelemetryClient.trackDependency (C:\test\node_modules\applicationinsights\out\Library\TelemetryClient.js:93:14)

**Code sample (Old version 1.4.2) working one**
**Breaking file path** : node_modules\applicationinsights\out\Library\EnvelopeFactory.js
**Line no:** 97

EnvelopeFactory.createDependencyData = function (telemetry) {
        var remoteDependency = new Contracts.RemoteDependencyData();
        **remoteDependency.name = telemetry.name;**
        remoteDependency.data = telemetry.data;
        remoteDependency.target = telemetry.target;
        remoteDependency.duration = Util.msToTimeSpan(telemetry.duration);
        remoteDependency.success = telemetry.success;
        remoteDependency.type = telemetry.dependencyTypeName;
        remoteDependency.properties = telemetry.properties;
        remoteDependency.resultCode = (telemetry.resultCode ? telemetry.resultCode + '' : '');
        if (telemetry.id) {
            remoteDependency.id = telemetry.id;
        }
        else {
            remoteDependency.id = Util.w3cTraceId();
        }
        var data = new Contracts.Data();
        data.baseType = Contracts.telemetryTypeToBaseType(Contracts.TelemetryType.Dependency);
        data.baseData = remoteDependency;
        return data;
    };

**Code sample (updated version 1.7.2) breaking one**
**Breaking file path** : node_modules\applicationinsights\out\Library\EnvelopeFactory.js
**Line no:** 100

`
EnvelopeFactory.createDependencyData = function (telemetry) {
        var remoteDependency = new Contracts.RemoteDependencyData();
        **remoteDependency.name = telemetry.name.length > 1024 ? telemetry.name.slice(0, 1021) + '...' : telemetry.name;**
        remoteDependency.data = telemetry.data;
        remoteDependency.target = telemetry.target;
        remoteDependency.duration = Util.msToTimeSpan(telemetry.duration);
        remoteDependency.success = telemetry.success;
        remoteDependency.type = telemetry.dependencyTypeName;
        remoteDependency.properties = telemetry.properties;
        remoteDependency.resultCode = (telemetry.resultCode ? telemetry.resultCode + '' : '');
        if (telemetry.id) {
            remoteDependency.id = telemetry.id;
        }
        else {
            remoteDependency.id = Util.w3cTraceId();
        }
        var data = new Contracts.Data();
        data.baseType = Contracts.telemetryTypeToBaseType(Contracts.TelemetryType.Dependency);
        data.baseData = remoteDependency;
        return data;
    };

`

**How to do a quick fix**: Please check whether the value is undefined/null before doing any operation(length/slice) on it.

**Comment by utkarsh-globant** [comment]
@markwolff : Thank you for fixing this. 👍
