### ISSUE TITLE
ERROR in ./node_modules/diagnostic-channel-publishers/dist/src/mysql.pub.js when building with electron-forge-webpack

### ISSUE THREAD

**Issue by kbalazs-ms** [microsoft/ApplicationInsights-node.js#705]
I've installed the applicationinsigths package to my electron application, initialized it from the main thread and I've managed to send out the custom track events I wanted, but as soon as I'm not running a debug build, and I try to 'make' or 'publish' the application using electon-forge (with webpack built in), I get the following warning and error messages.

I don't really care about the warning (if it won't block my build / publish process) but the errors are keeping me from this goal:

```
WARNING in ./node_modules/applicationinsights/out/AutoCollection/NativePerformance.js
Module not found: Error: Can't resolve 'applicationinsights-native-metrics' in 'C:\Work\git\sl-desktop\node_modules\applicationinsights\out\AutoCollection'
 @ ./node_modules/applicationinsights/out/AutoCollection/NativePerformance.js
 @ ./node_modules/applicationinsights/out/applicationinsights.js
 @ ./src/managers/applicationInsightsManager.ts
 @ ./src/main.ts

ERROR in ./node_modules/diagnostic-channel-publishers/dist/src/mysql.pub.js
Module not found: Error: Can't resolve '→/lib/Connection' in 'C:\Work\git\sl-desktop\node_modules\diagnostic-channel-publishers\dist\src'
 @ ./node_modules/diagnostic-channel-publishers/dist/src/mysql.pub.js 55:26-58
 @ ./node_modules/diagnostic-channel-publishers/dist/src/index.js
 @ ./node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/initialization.js
 @ ./node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js
 @ ./node_modules/applicationinsights/out/applicationinsights.js
 @ ./src/managers/applicationInsightsManager.ts
 @ ./src/main.ts

ERROR in ./node_modules/diagnostic-channel-publishers/dist/src/mysql.pub.js
Module not found: Error: Can't resolve '→/lib/Pool' in 'C:\Work\git\sl-desktop\node_modules\diagnostic-channel-publishers\dist\src'
 @ ./node_modules/diagnostic-channel-publishers/dist/src/mysql.pub.js 70:20-46
 @ ./node_modules/diagnostic-channel-publishers/dist/src/index.js
 @ ./node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/initialization.js
 @ ./node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js
 @ ./node_modules/applicationinsights/out/applicationinsights.js
 @ ./src/managers/applicationInsightsManager.ts
 @ ./src/main.ts
    at cb (C:\Work\git\sl-desktop\node_modules\@electron-forge\plugin-webpack\src\WebpackPlugin.ts:250:31)
    at finalCallback (C:\Work\git\sl-desktop\node_modules\webpack\lib\Compiler.js:257:39)
    at C:\Work\git\sl-desktop\node_modules\webpack\lib\Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Work\git\sl-desktop\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Work\git\sl-desktop\node_modules\tapable\lib\Hook.js:154:20)
    at onCompiled (C:\Work\git\sl-desktop\node_modules\webpack\lib\Compiler.js:271:21)
    at C:\Work\git\sl-desktop\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Work\git\sl-desktop\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Work\git\sl-desktop\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Work\git\sl-desktop\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Work\git\sl-desktop\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)      
    at AsyncSeriesHook.lazyCompileHook (C:\Work\git\sl-desktop\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Work\git\sl-desktop\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Work\git\sl-desktop\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)      
    at AsyncSeriesHook.lazyCompileHook (C:\Work\git\sl-desktop\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Work\git\sl-desktop\node_modules\webpack\lib\Compilation.js:1414:32
    at eval (eval at create (C:\Work\git\sl-desktop\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Work\git\sl-desktop\node_modules\webpack\node_modules\terser-webpack-plugin\dist\index.js:321:9
    at step (C:\Work\git\sl-desktop\node_modules\webpack\node_modules\terser-webpack-plugin\dist\TaskRunner.js:87:9)
    at done (C:\Work\git\sl-desktop\node_modules\webpack\node_modules\terser-webpack-plugin\dist\TaskRunner.js:98:30)
    at tryCatcher (C:\Work\git\sl-desktop\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Work\git\sl-desktop\node_modules\bluebird\js\release\promise.js:547:31)
```

Can someone point me to the right direction what am I doing wrong here? 
Thanks in advance!

**Comment by hectorhdzg** [comment]
@kbalazs-ms do you have a repo where we can reproduce this issue?, or if can provide more details to reproduce on our end would be good as well.

**Comment by alminQSD** [comment]
I'm currently working on the same project where I'm integrating Microsoft App Insights. I've encountered the same issues as those highlighted in an earlier post by my colleague @kbalazs-ms, specifically when trying to 'make' or 'publish' the application using electron-forge with webpack.

When I'm not running a debug build, the system outputs an error message https://github.com/microsoft/ApplicationInsights-node.js/issues/705#issue-753727659. This, of course, disrupts the overall development process, leading to an inefficient workflow. I've tried several methods to troubleshoot the problem but have not been successful so far.

To assist in resolving this issue, I have prepared a minimal project that reproduces the issue consistently by running "npm run make". You can access it here: https://drive.google.com/file/d/1Eqad5h8hcPITQZ26o2A8k2MZcuyf5Pst/view?usp=sharing. 
I believe this will help you in understanding and resolving the issue at hand.

I am hopeful that we can find a solution to this problem together. Any insights or guidance from the community would be greatly appreciated.

@hectorhdzg

**Comment by hectorhdzg** [comment]
@alminQSD can you share the Node.js runtime version you have installed in your machine, apparently also using Python so if you can share the version as well it would be useful. Getting some errors when doing npm install

pm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild --release
npm ERR! prebuild-install warn install No prebuilt binaries found (target=20.2.0 runtime=node arch=x64 libc= platform=win32)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@20.2.0 | win32 | x64
npm ERR! gyp info find Python using Python version 2.7.14 found at "C:\Python27\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.33801.447) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'

**Comment by alminQSD** [comment]
@hectorhdzg Sure, I am using Node.js version 14.17.6 and Python version 3.10.8 on my machine.

**Comment by hectorhdzg** [comment]
@alminQSD I'm not webpack expert, but adding externals config and adding diagnostic-channel-publishers make the error disappear, looks like it doesn't like dynamic loading of libraries and that is exactly what diagnostic channel package is doing, feels like this is an issue with webpack configuration and not something we can fix in our side, [reference](https://github.com/microsoft/ApplicationInsights-node.js/issues/1102#issuecomment-1460774445)

**Comment by hectorhdzg** [comment]
@alminQSD diagnostic-channel-publishers should never work in the browser, that is a module for Node.js runtime only, same as this SDK, if you want to run Application Insights in the browser you need to use  https://github.com/microsoft/ApplicationInsights-js

**Comment by alminQSD** [comment]
@hectorhdzg I appreciate your response and understand your perspective. However, the scenario I’m dealing with is slightly different. Electron, the technology I’m working with, combines Node.js and Chromium, allowing Node.js runtime to be used within the context of a web application. This offers the ability to leverage modules typically limited to the server-side, such as the Application Insights SDK for Node.js, directly within the Electron application.

A choice of the Application Insights for Node.js, as opposed to the browser-specific version, is in line with the recommendations for Electron apps.

Notably, the Application Insights SDK for Node.js operates seamlessly within the Electron environment in development mode. This leads me to believe that the conflict is not inherent in using the Node.js SDK within Electron, but rather a packaging or configuration issue that surfaces when bundling the app for production.

If you have any further insights or possible solutions to suggest I would be grateful. Thanks again for your time and assistance.

**Comment by alminQSD** [comment]
@hectorhdzg I want to clarify that I'm not trying to run Application Insights in the browser. Instead, I'm utilizing the Node.js runtime in Electron. As you might know, Electron provides two types of processes: the 'main' process which runs Node.js, and the 'renderer' processes, which are essentially web pages.

My implementation of Application Insights is within the 'main' process, which is [recommended](https://techcommunity.microsoft.com/t5/modern-work-app-consult-blog/add-telemetry-to-your-electron-application-with-application/ba-p/802091) by Microsoft, so it is indeed running within a Node.js environment, not a traditional browser context. 

Would you be able to review a project I sent to you and perhaps shed some light on any mistakes or oversights on my end? Your input would be invaluable to us.

Looking forward to your response.

**Comment by hectorhdzg** [comment]
Sorry @alminQSD I was on vacation for a few weeks, if it would be worth a try to use latest beta version of this package, auto instrumentation of external libraries is handled differently and could be easier to integrate with your bundling, looks like the error you shared last month is specific to your javascript file not bundling correctly, so not sure how we can fix that on our side, please give a try with beta version and let me know how it goes.
https://github.com/microsoft/ApplicationInsights-node.js/tree/beta#readme

**Comment by alminQSD** [comment]
@hectorhdzg 

Thank you for your suggestion to use the latest beta version of the Application Insights package. I've given it a try, but unfortunately, I've encountered an issue when starting the app.

To reproduce the issue, please follow these steps:

1. Clone the [repository](https://drive.google.com/file/d/1wAirVy4Yr2_SQDy4b-U0t0uO0TaHL2t0/view?usp=sharing) and navigate to the project directory.
2. Run npm install to install the required Node.js modules.
3. Start the application using the _npm run start-dev_ command.
After these steps, the error should manifest itself. I believe seeing this firsthand could provide a better understanding of the issue we're encountering.

Looking forward to your feedback and further guidance. Thanks again for your continued assistance.

<img width="557" alt="Screenshot 2023-08-07 at 13 44 51" src="https://github.com/microsoft/ApplicationInsights-node.js/assets/97589739/71369690-7454-498b-b4b3-c658e827301c">

**Comment by mdivkovic-speech** [comment]
@hectorhdzg, I'm working with Almin, and we are trying to tackle this issue again. Is there anything new on this front from your side? Any other suggestions we can try after Almin's last comment? Thank you in advance!
