### ISSUE TITLE
[Help] Structured logging

### ISSUE THREAD

**Issue by Looooopy** [microsoft/ApplicationInsights-node.js#706]
I try to keep my logs structured in a json file but then something fails in application Insights i get a console output in multiple lines.

__Something like this__

````
ApplicationInsights:Sender [
 'Ingestion endpoint could not be reached 5 consecutive times. There may be resulting telemetry loss. Most recent error:',
     at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:120:14) {
      syscall: 'connect',
      port: 443
      errno: 'ETIMEDOUT',
      Error: connect ETIMEDOUT 52.169.64.244:443
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
    code: 'ETIMEDOUT',
    address: '52.169.64.244',
  }
]
````

But what i do with other logging is format it as json and output it to a single line

Is there a way to customise it in Application Insight framework?

**Comment by hectorhdzg** [comment]
@Looooopy unfortunately the SDK doesn't support configuration to allow custom loggers to be used.

**Comment by Looooopy** [comment]
@hectorhdzg  Is that something you guys could do or is it something you would like someone to do in a pull request?

**Comment by hectorhdzg** [comment]
@Looooopy it would be great if you can send a PR for this, this is a low priority task for us so it could take some time to have it ready

**Comment by jmealo** [comment]
@hectorhdzg: I have a PR open for this #733
