### ISSUE TITLE
ERR_HTTP_HEADERS_SENT

### ISSUE THREAD

**Issue by nulltoken** [microsoft/ApplicationInsights-node.js#751]
**Lib versions:**
- "applicationinsights": "1.8.10",
- "applicationinsights-native-metrics": "0.0.6"

**Node:** 14.16.1
**OS:** Alpine 3.13.4

```
ApplicationInsights:Request-Context header could not be set. Correlation of requests may be lost [
  Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
      at ClientRequest.setHeader (_http_outgoing.js:558:11)
      at Function.Util.safeIncludeCorrelationHeader (/app/node_modules/applicationinsights/out/Library/Util.js:325:21)
      at Function.AutoCollectHttpDependencies.trackRequest (/app/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:137:26)
      at clientRequestPatch (/app/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:52:45)
      at https.request (/app/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:74:13)
      at Request._makeRequest (/app/node_modules/got/dist/source/core/index.js:1124:43)
      at /app/node_modules/got/dist/source/core/index.js:328:28
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    code: 'ERR_HTTP_HEADERS_SENT'
  }
]
ApplicationInsights:Correlation headers could not be set. Correlation of requests may be lost. [
  Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
      at ClientRequest.setHeader (_http_outgoing.js:558:11)
      at Function.AutoCollectHttpDependencies.trackRequest (/app/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:144:43)
      at clientRequestPatch (/app/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:52:45)
      at https.request (/app/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:74:13)
      at Request._makeRequest (/app/node_modules/got/dist/source/core/index.js:1124:43)
      at /app/node_modules/got/dist/source/core/index.js:328:28
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    code: 'ERR_HTTP_HEADERS_SENT'
  }
]
```

We've started to see this happening in a TEST environment following a deployment on March 3rd (commit 32ade704). This commit didn't bring any meaningful changes to the code of the dependencies.
Previous deployment on that environment happened on March 2nd (commit cabb09a4ec) and didn't generate any of those messages.

Only meaningful thing that we've been able to track down was that the underlying Node version we were running on changed.
Deployment generating those messages was running on top of Node 14.16.0.
Previous deployment was running on top of Node 14.15.5

**Comment by nulltoken** [comment]
This is very consistent and happens on a daily basis. 
These messages are generated for ~x% of our daily traffic (where 0.091 <= x < =7.837)
As this is a test environment, it doesn't get hit a lot. The daily traffic since March 3rd varies between 68k and 243k daily requests.

**Comment by nulltoken** [comment]
We eventually made some progress. It looks like some of our clients decided that sending a `expect`: `100-continue` header would be an interesting experience.

Would you have guidance/experience with regards to usage of applicationinsights in a Node context and dealing with this header?

**Comment by hectorhdzg** [comment]
@nulltoken looks like the moment the outgoing request have this header the SDK cannot set custom headers anymore, this is not critical issue because is just failing to add the correlation header to the request that is still not completely done and it would be added once the expect header is not present anymore, you can turn off internal logging if this adding to much noise, or disable correlation injection for a specific domain using [correlationHeaderExcludedDomains](https://github.com/microsoft/ApplicationInsights-node.js#advanced-configuration-options)

**Comment by 0Dmitry** [comment]
How can I turn off this internal logging for app insights?

**Comment by hectorhdzg** [comment]
@0Dmitry you can use enableInternalDebugLogging, there is more info [here](https://github.com/microsoft/ApplicationInsights-node.js#configuration)
