### ISSUE TITLE
Not able to handle circular JSON structure

### ISSUE THREAD

**Issue by ghost** [microsoft/ApplicationInsights-node.js#774]
When sending telemetry data as a result of a failed dependency call via Axios, ApplicationInsights throws an exception due to a circular structure:

```
ApplicationInsights:Failed to serialize payload [
   TypeError: Converting circular structure to JSON
       --> starting at object with constructor 'TLSSocket'
       |     property '_httpMessage' -> object with constructor 'ClientRequest'
       --- property 'socket' closes the circle
       at JSON.stringify (<anonymous>)
       at Channel._stringify (./node_modules/applicationinsights/out/Library/Channel.js:89:25)
       at Channel.send (./node_modules/applicationinsights/out/Library/Channel.js:39:28)
       at NodeClient.TelemetryClient.track (./node_modules/applicationinsights/out/Library/TelemetryClient.js:131:30)
       at NodeClient.TelemetryClient.trackTrace (./node_modules/applicationinsights/out/Library/TelemetryClient.js:51:14)
       at ./node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/winston.sub.js:46:20
       at Array.forEach (<anonymous>)
       at subscriber (./node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/winston.sub.js:37:13)
       at ./node_modules/diagnostic-channel/dist/src/channel.js:43:25
       at Array.forEach (<anonymous>),
   Envelope {
     ver: 1,
     sampleRate: 100,
     tags: {
       'ai.application.ver': '1.3.7',
       'ai.device.id': '',
       'ai.cloud.roleInstance': 'serverName',
       'ai.device.osVersion': 'Linux 4.18.0-193.47.1.el8_2.x86_64',
       'ai.cloud.role': 'Web',
       'ai.device.osArchitecture': 'x64',
       'ai.device.osPlatform': 'linux',
       'ai.internal.sdkVersion': 'node:1.8.10',
       'ai.operation.id': 'c24aa443ce9449aa82e04afaed6f8bf3',
       'ai.operation.name': 'GET /some/path',
       'ai.operation.parentId': '|c24aa443ce9449aa82e04afaed6f8bf3.d942c472d22e4968.'
     },
     data: Data { baseType: 'MessageData', baseData: [MessageData] },
     iKey: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
     name: 'Microsoft.ApplicationInsights.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.Message',
     time: '2021-06-10T05:00:00.422Z'
   }
 ]
```

I don't have visibility into the object being serialized, so I don't know what makes it circular. Is there a way to make the library more robust to handle circular structures in a graceful way?

Thanks!

**Comment by hectorhdzg** [comment]
@mattp-rab Application Insights must not throw an exception when this happens, it must be handled internally and generate warning log like the one you shared, please confirm if you are seeing an exception being triggered, if that is the case we will need more info regarding your winston implementation and versions to try to reproduce the issue, if you provide more details about the malformed envelope we may be able to improve the SDK to handle it better if possible.
