### ISSUE TITLE
2.1.6 Breaking changes

### ISSUE THREAD

**Issue by papabytes** [microsoft/ApplicationInsights-node.js#829]
Hi everyone,

We recently updated from 2.1.5 to 2.1.6 and, without changing any source code we started seeing the following error on the startup of our application:

``
ApplicationInsights:The URL object is failed to create. [
  TypeError [ERR_INVALID_URL]: Invalid URL: Azure.KeyVault.Secrets.SecretClient.getSecret
      at onParseError (internal/url.js:279:9)
      at new URL (internal/url.js:355:5)
      at NodeClient.TelemetryClient.trackDependency (/app/node_modules/applicationinsights/out/Library/TelemetryClient.js:106:36)
      at /app/node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/azure-coretracing.sub.js:29:28
      at Array.forEach (<anonymous>)
      at /app/node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/azure-coretracing.sub.js:22:21
      at Function.CorrelationContextManager.runWithContext (/app/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:65:20)
      at OpenTelemetryScopeManagerWrapper.with (/app/node_modules/applicationinsights/out/AutoCollection/AsyncHooksScopeManager.js:39:70)
      at subscriber (/app/node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/azure-coretracing.sub.js:21:56)
      at /app/node_modules/diagnostic-channel/dist/src/channel.js:44:25 {
    input: 'Azure.KeyVault.Secrets.SecretClient.getSecret',
    code: 'ERR_INVALID_URL'
  }
]
``

Reverting back to 2.1.5 was our approach since we could not figure out what to change on our end.

Thank you for your time.

**Comment by thebenlamm** [comment]
Same on Node:v14.17.6

"dependencies": {
   "@azure/service-bus": "7.3.0",
   "@azure/storage-blob": "12.7.0",
   "applicationinsights": "2.1.6",
}

and can confirm that reverting back to 2.1.5 fixes the problem.

**Comment by josendf-basetis** [comment]
Same issue here:

Node: v14.17.5

OS: Windows and Linux 

```
    "dependencies": {
        "@azure/storage-blob": "12.7.0",
        "@azure/storage-queue": "12.6.0",
        "applicationinsights": "2.1.6"
    }
```

```
ApplicationInsights:The URL object is failed to create. [
  TypeError [ERR_INVALID_URL]: Invalid URL: Azure.Storage.Queue.QueueClient-receiveMessages
      at onParseError (internal/url.js:279:9)
      at new URL (internal/url.js:355:5)
      at NodeClient.TelemetryClient.trackDependency (server\node_modules\applicationinsights\out\Library\TelemetryClient.js:106:36)
      at server\node_modules\applicationinsights\out\AutoCollection\diagnostic-channel\azure-coretracing.sub.js:29:28
      at Array.forEach (<anonymous>)
      at server\node_modules\applicationinsights\out\AutoCollection\diagnostic-channel\azure-coretracing.sub.js:22:21
      at clsBind (server\node_modules\cls-hooked\context.js:172:17)
      at Function.CorrelationContextManager.runWithContext (server\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:62:131)
      at OpenTelemetryScopeManagerWrapper.with (server\node_modules\applicationinsights\out\AutoCollection\AsyncHooksScopeManager.js:39:70)
      at subscriber server\node_modules\applicationinsights\out\AutoCollection\diagnostic-channel\azure-coretracing.sub.js:21:56)
      at server\node_modules\diagnostic-channel\dist\src\channel.js:44:25
      at Array.forEach (<anonymous>)
      at ContextPreservingEventEmitter.publish (server\node_modules\diagnostic-channel\dist\src\channel.js:40:23)
      at Span.span.end (server\node_modules\diagnostic-channel-publishers\dist\src\azure-coretracing.pub.js:62:62)
      at QueueClient.receiveMessages (server\node_modules\@azure\storage-queue\dist\index.js:5107:18)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    input: 'Azure.Storage.Queue.QueueClient-receiveMessages',
    code: 'ERR_INVALID_URL'
  }
]
```
