### ISSUE TITLE
ApplicationInsights crashes on the container start with the ((TypeError: api_1.createContextKey is not a function)) excption

### ISSUE THREAD

**Issue by auxfix** [microsoft/ApplicationInsights-node.js#913]
**our setup**
  - Azure App Service
  - Docker
 - node:10.16.0
 - we use ssh inside docker
 - we are trying to telemetry node.js api with ApplicationInsights-node_

when we did everything locally following by this instruction 
**_https://docs.microsoft.com/en-us/azure/azure-monitor/app/nodejs_**

 - we could see all telemetry on the app insight portal in the azure portal tab.
- but when we started trying to deploy that solution to the dev stand we have got problems.

1. First our build pipeline started crashing. I fixed it by updating the typescript version in our package.json. It was some 3rd version, I replaced it with 4.1.2 and reinstall node_modules.
 Build became successful.
2. But now our node application crashing with the node js exception after each attempt to start the container inside of the azure web app
3. Somewhere I read what it could be somehow connected to the other azure npm modules we use, here are the list:     
  **"@azure/storage-queue": "^12.4.0",
    "azure-storage": "^2.10.4",**

4. here is an exception:

`2022-02-01T12:47:57.908240807Z TypeError: api_1.createContextKey is not a function
2022-02-01T12:47:57.908266308Z     at Object.anonymous (/airofit-api/node_modules/@opentelemetry/core/build/src/trace/suppress-tracing.js:20:36)
2022-02-01T12:47:57.908273008Z     at Module._compile (internal/modules/cjs/loader.js:776:30)
2022-02-01T12:47:57.908276609Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2022-02-01T12:47:57.908280109Z     at Module.load (internal/modules/cjs/loader.js:653:32)
2022-02-01T12:47:57.908289309Z     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2022-02-01T12:47:57.908292609Z     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2022-02-01T12:47:57.908295909Z     at Module.require (internal/modules/cjs/loader.js:690:17)
2022-02-01T12:47:57.908299610Z     at Module.patchedRequire [as require] (/airofit-api/node_modules/diagnostic-channel/dist/src/patchRequire.js:15:46)
2022-02-01T12:47:57.908303210Z     at require (internal/modules/cjs/helpers.js:25:18)
2022-02-01T12:47:57.908306510Z     at Object.anonymous (/airofit-api/node_modules/@opentelemetry/core/build/src/baggage/propagation/HttpBaggagePropagator.js:20:28)`

**Comment by auxfix** [comment]
One observation. without app insight install i have the following dependency chain in my `yarn-lock`

```
_"@azure/storage-queue@^12.4.0":
  version "12.7.0"
  resolved "https://registry.yarnpkg.com/@azure/storage-queue/-/storage-queue-12.7.0.tgz#ab25d3c5a050ce0ae5faedcd7c907621e124ec85"
  integrity sha512-yS27do9Dn3ohaOHWIwZfyu+I3gG0QJWNCl+qTLmsyWxBz5KO3O+clQ+NYo9tvovPBkBftf3kY2K705AeH0o0SQ==
  dependencies:
    "@azure/abort-controller" "^1.0.0"
    **@azure/core-http" "^2.0.0**
    "@azure/core-paging" "^1.1.1"
    "@azure/core-tracing" "1.0.0-preview.13"
    "@azure/logger" "^1.0.0"
    tslib "^2.2.0"_
```
|
|
|
\|/

```
"@azure/core-tracing@1.0.0-preview.13":
  version "1.0.0-preview.13"
  resolved "https://registry.yarnpkg.com/@azure/core-tracing/-/core-tracing-1.0.0-preview.13.tgz#55883d40ae2042f6f1e12b17dd0c0d34c536d644"
  integrity sha512-KxDlhXyMlh2Jhj2ykX6vNEU0Vou4nHr025KoSEiz7cS3BNiHNaZcdECk/DmLkEB0as5T7b/TpRcehJ5yV6NeXQ==
  dependencies:
    "@opentelemetry/api" "^1.0.1"
    tslib "^2.2.0"
```


**### but after installation of the app insight npm i have got:**

```
_applicationinsights@^2.2.1:
  version "2.2.1"
  resolved "https://registry.yarnpkg.com/applicationinsights/-/applicationinsights-2.2.1.tgz#89d509b26a4f9dce6e3351da73061c986565d1b0"
  integrity sha512-N6panMyjw6E6ayCgjFDBmL/NkaolgBgeX1iJ0jh50E6wrncVJBCa+I4IelwwOfJ4Dl9BWzOSLjp84wTiUyhNwg==
  dependencies:
    "@azure/core-http" "^2.2.3"
    "@opentelemetry/api" "^1.0.4"
    "@opentelemetry/core" "^1.0.1"
    "@opentelemetry/sdk-trace-base" "^1.0.1"
    "@opentelemetry/semantic-conventions" "^1.0.1"
    cls-hooked "^4.2.2"
    continuation-local-storage "^3.2.1"
    diagnostic-channel "1.1.0"
    diagnostic-channel-publishers "1.0.4":
```
|
|
|
|
\|/


```
"@opentelemetry/api@^1.0.1", "@opentelemetry/api@^1.0.4":
  version "1.0.4"
  resolved "https://registry.yarnpkg.com/@opentelemetry/api/-/api-1.0.4.tgz#a167e46c10d05a07ab299fc518793b0cff8f6924"
  integrity sha512-BuJuXRSJNQ3QoKA6GWWDyuLpOUck+9hAXNMCnrloc1aWVoy6Xq6t9PUV08aBZ4Lutqq2LEHM486bpZqoViScog==
```

could not it be some  way of conflict between: "@opentelemetry/api@^1.0.1" and "@opentelemetry/api@^1.0.4":

**Comment by hectorhdzg** [comment]
@auxfix are you getting any error while installing your dependencies?, there are no breaking changes with @opentelemetry/api versions you have, looks like the package is not even there by looking at the error, can you verify if the code is available in node_modules folder?, I tried to reproduce using @azure/storage-queue with no luck.

**Comment by auxfix** [comment]
Hi @hectorhdzg! Thank you so much for so fast response!!!!  **applicationinsights** npm is in the package.json. Actually, as soon as I add it there it started crashing inside of the container in App Service. (again locally all is perfect) You know, i will do the following thing, i will deploy my code, connect to the docker by SSH, and will look inside my **package.json** and **node_modules** folder. Just to clarify. should i find there only **@opentelemetry** folder, or some other dependencies needed?

**Comment by auxfix** [comment]
Hi @hectorhdzg, unfortunately, i could not connect to the Docker container because appinsight crash right on the node start, and do not let the container start. But here the logs which i have right before the crash:

**### NO ID] 2022-02-16 07:45:51 [32minfo[39m: !!!!appInsightConnectionString = InstrumentationKey=00000000-00000-00000-0000000000;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/ string end**


2022-02-16T07:45:51.353675110Z TypeError: api_1.createContextKey is not a function
2022-02-16T07:45:51.353700611Z     at Object.<anonymous> (/airofit-api/node_modules/@opentelemetry/core/build/src/trace/suppress-tracing.js:20:36)
2022-02-16T07:45:51.353707412Z     at Module._compile (internal/modules/cjs/loader.js:776:30)
2022-02-16T07:45:51.353711912Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2022-02-16T07:45:51.353716112Z     at Module.load (internal/modules/cjs/loader.js:653:32)
2022-02-16T07:45:51.353720212Z     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2022-02-16T07:45:51.353730013Z     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2022-02-16T07:45:51.353734713Z     at Module.require (internal/modules/cjs/loader.js:690:17)
2022-02-16T07:45:51.353738613Z     at Module.patchedRequire [as require] (/airofit-api/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
2022-02-16T07:45:51.353742813Z     at require (internal/modules/cjs/helpers.js:25:18)
2022-02-16T07:45:51.353746813Z     at Object.<anonymous> (/airofit-api/node_modules/@opentelemetry/core/build/src/baggage/propagation/W3CBaggagePropagator.js:20:28)


the first line is a comment, in which I printed the connection string, to be sure it's passed. I put zeroes to hide the numbers.

also here is part of or node modules:
```

    "@azure/storage-queue": "^12.4.0",
    "@types/heapdump": "^0.3.1",
    "@types/numeral": "^2.0.2",
    "applicationinsights": "^2.2.0",
    "axios": "^0.21.1",
    "azure-storage": "^2.10.4",
```
i am pretty sure it is on the server as well


and here how i config app insight on the start:

```
const configService = new ConfigService();

const appInsightConfig = configService.getAppInsightConfig();
const appInsightConnectionString = appInsightConfig.connectionString;
const collect3rdPartyLoggers = parseConfigValue(appInsightConfig.collect3rdPartyLoggers, 'boolean') as boolean;
const collectConsoleLogs = parseConfigValue(appInsightConfig.collectConsoleLogs, 'boolean') as boolean;
const samplingPercent = parseConfigValue(appInsightConfig.samplingPercent, 'number') as number;

logger.info(`!!!!appInsightConnectionString = ${appInsightConnectionString} string end`);
appInsights.setup(appInsightConnectionString)
  .setAutoDependencyCorrelation(true)
  .setAutoCollectRequests(true)
  .setAutoCollectPerformance(true, true)
  .setAutoCollectExceptions(true)
  .setAutoCollectDependencies(true)
  .setAutoCollectConsole(collect3rdPartyLoggers, collectConsoleLogs)
  .setUseDiskRetryCaching(true)
  .setSendLiveMetrics(false)
  .setDistributedTracingMode(appInsights.DistributedTracingModes.AI)
  .start();

appInsights.defaultClient.config.samplingPercentage = samplingPercent;
```

**Comment by eeropenttinen** [comment]
I had a similar issue. The solution [here](https://stackoverflow.com/questions/69303827/appinsights-setup-start-returns-an-error) resolved my issue. I updated the version of @azure/storage-blob and that did the trick.

**Comment by auxfix** [comment]
Hi guys, my attempt to upgrade the old SDK package will be delayed cause the new package API is quite different, and i need time to rewrite a service that is using it. So it is up to the administration to decide to keep this issue open or close it when i will be able to apply the upgrade and will have a result.

I only want to add what is was communicating with the Azure support in parallel, and they have the same advice as @eeropenttinen told - upgrade all old Azure SDK npm packages.
