### ISSUE TITLE
TypeError: Cannot read property 'TELEMETRY_SDK_NAME' of undefined 

### ISSUE THREAD

**Issue by luciantr24** [microsoft/ApplicationInsights-node.js#925]
Hello, we have a node.js  microservice which is running on azure (windows machine with node 10.15.2 version), we were using **applicationinsights** version **2.2.0**, after updating to version _2.2.1 or 2.2.2_ an error started to occur when starting the application on the server . (locally there is no issue, I was able to run the application with both _2.2.1 and 2.2.2_). I checked also the files and everything looks fine on the server.

 This is the error message:

2022-03-17T13:37:59  Error       TypeError: Cannot read property 'TELEMETRY_SDK_NAME' of undefined
2022-03-17T13:37:59  Error           at Object.<anonymous> (-serverpath-\node_modules\@opentelemetry\core\build\src\platform\node\sdk-info.js:23:56)
2022-03-17T13:37:59  Error           at Module._compile (internal/modules/cjs/loader.js:689:30)
2022-03-17T13:37:59  Error           at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2022-03-17T13:37:59  Error           at Module.load (internal/modules/cjs/loader.js:599:32)
2022-03-17T13:37:59  Error           at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2022-03-17T13:37:59  Error           at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2022-03-17T13:37:59  Error           at Module.require (internal/modules/cjs/loader.js:637:17)
2022-03-17T13:37:59  Error           at Module.patchedRequire [as require] (-serverpath-\node_modules\diagnostic-channel\dist\src\patchRequire.js:16:46)
2022-03-17T13:37:59  Error           at require (internal/modules/cjs/helpers.js:22:18)
2022-03-17T13:37:59  Error           at Object.<anonymous> (-serverpath-\node_modules\@opentelemetry\core\build\src\platform\node\index.js:33:14)

Anyone knows what could be the issue?

**Comment by luciantr24** [comment]
@hectorhdzg No, we are not using any OpenTelemetry package in our project. I've installed @opentelemetry/core@1.0.1 in our project as you suggested and the issue has been solved.

**Comment by hectorhdzg** [comment]
@luciantr24 I'm not able to reproduce the issue in my side using @opentelemetry/core@1.1.0, if you can provide more details we can fix the root cause, so you don't have to install manually a specific version of that package and you actually get latest updates, sharing the Azure SDKs you are using including the versions of the packages and Application Insights SDK initialization code would be useful for us to understand the problem better

**Comment by luciantr24** [comment]
Hello @hectorhdzg . I did some package fixing in the service as we had some warnings on a package version. I uninstalled @opentelemetry/core and updated the dependency **node-fetch from 2.6.5 to 2.6.7** (required by @azure/core-http).  Everything is working as expected in Azure now without any issue with **applicationinsights** version **2.2.2** and no direct reference of @opentelemetry/core in the package.json.
